### ISSUE TITLE
Major: Fallen London UI overhaul landed

### ISSUE THREAD

**Issue by Zarremgregarrok** [hash-bang/gadzooks#9]
Major Fallen London UI overhaul landed.
Fortunately URL also changed, so all scripts are automatically disabled. (since they were looking for old URL)

But that also means your addon is not working.

I expect that means the end of your support for Gadzooks, since you do not play FL anymore, right?

**Comment by hash-bang** [comment]
Yeah, its pretty much an abandoned project now.

I've honestly no idea the work involved with fixing up the scripts or the project as I've not had time to go though it.

Hopefully someone else might take over in the future.

**Comment by Zarremgregarrok** [comment]
Many of the features are already covered by the UI redesign (making site mobile friendly) and others will soon be covered by other addons.

Enjoy your freedom from this addon. ;)

**Comment by hash-bang** [comment]
Haha. Yeah, I'm glad they fixed up some of the irritants.
I'll mark it as archived.
